### ISSUE TITLE
Cygwin echo $PATH

### ISSUE THREAD

**Issue by 7fe** [gnp/psh#13]
How do I get the following to work?

```
echo $PATH
```

alternatively what about the following?

```
$test="test"
#1st line doesn't work
echo $test
print($test)
```

EDIT(On Cygwin):

```
psh: Warning: $Psh::prompt or PS1/2 environment variables contain unknown escape sequence '\a'.
PS1="\[\e]0;\w\]\n\[\e[32m\]\u@\h \[\e[33m\]\w\[\e[0m\]\n\$"
```

**Comment by mklement0** [comment]
The [INSTALL](https://github.com/gnp/psh/blob/master/INSTALL) file has the answer:

> Currently, psh works on any modern Unix system with perl5.

If a REPL rather than a full shell will do, consider my [`perli` REPL](https://github.com/mklement0/perli), which also runs on Windows, with certain limitations.

**Comment by limeblack** [comment]
@mklement0  Have you tried it with Cygwin or are you saying that this is a lost cause basically?

**Comment by mklement0** [comment]
@limeblack Good question; no, I haven't tried on Cygwin; do provide feedback here if you try it.

As for the general state of this project: I'm not affiliated with it, so I can't speak for the maintainers, but it's fair to say that there's been very little activity in a long time.

**Comment by limeblack** [comment]
@mklement0  It looks like we both missed it but there is a install.win32 so it appears it has once run on windows.

**Comment by mklement0** [comment]
@limeblack Thanks for letting me know.

**Comment by 7fe** [comment]
@mklement0 Do you know have to make something like the following work?

```
$test="test"
#1st line doesn't work
echo $test
print($test)
```

**Comment by mklement0** [comment]
@limeblack: For reasons unknown to me, using Perl variables on a line that starts with an executable name such as `echo` only works if the variables are declared in a _package_ namespace:

```
 $vars::test="test"  # declare variable in a package namespace (any package name will do)
 echo $vars::test   # -> 'test'
```

Note that know shell is involved in the `echo` call, so you won't be able to pass _shell_ variable references through (they'll be treated as literals).

To _only_ pass shell variables through, you'd have to use

```
 !echo $HOME
```

If you wanted to combine expansion of _both_ types of variables, it gets tricky (note that there's no package requirement for the Perl variable in this case):

```
p!print `echo $test=\$HOME`
```

**Comment by 7fe** [comment]
@mklement0  thank you for the response it is much appreciated.

Do you think I could make `!` the default(because `echo $PATH` doesn't do anything) so I can at least use environments variables?
I found it defined in /lib/Psh/StrategyBunch.pm but I don't see how to make it a default.

I think part of the issue is that they essentially have 2 namespaces local variables and $env so your code wouldn't clash with $PATH and other variables.

**Comment by mklement0** [comment]
@limeblack: I'm glad I could help so far. However, I'm not using `psh` myself and therefore have no interest in digging deeper.

A quick read through the `man` page tells me that  you can use the psh built-in `strategy` to modify the set and order of evaluation strategies, but in your case you'd have to _modify_ the "executable" strategy to ensure involvement of the shell, which I don't  know how to do. 

Honestly, given the state of this project, I encourage you to consider alternatives.

Good luck.
